env:
- namespace: "backstage"
  companyname: "ACME Inc"
  gitopsnamespace: "assemble-argocd"
  gitopsinfranamespace: "infra-argocd"
  pipelinesnamespace: "assemble-pipelines"
  vaultconfignamespace: "vault-config-operator"
  vaultnamespace: "vault"
  gitwebhooknamespace: "gitwebhook-operator"
