apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/{{ .Values.git.infraOrgName }}/janus-platforms.git
        revision: {{ .Values.git.infraRevision }}
        files:
        - path: "clusters/**/config.json"
  template:
    metadata:
      name: '{{"{{"}}cluster.name{{"}}"}}'
    spec:
      project: default
      source:
        path: charts/apps
        repoURL: https://github.com/{{ .Values.git.infraOrgName }}/janus-platforms.git
        targetRevision: {{ .Values.git.infraRevision }}
        helm:
          parameters:
            - name: git.applicationId
              value: "{{ .Values.git.applicationId }}"
            - name: git.infraOrgName
              value: "{{ .Values.git.infraOrgName }}"
            - name: git.infraRevision
              value: "{{ .Values.git.infraRevision }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .Values.destination.namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
