replicaCount: 1

image:
  repository: quay.io/assemble/backstage
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rhsso:
  baseUrl: ""
  realm: backstage
  # The ID of the Keycloak Client
  clientId: ""
  # The Secret of the Keycloak Client
  clientSecret: ""
  # Enable the backstage plugin
  backstagePluginEnabled: false

oauth:
  enabled: false
  insecure: false
  cookieSecret: ""
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    pullPolicy: Always
    tag: "latest"
  resources:
    {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  port: 4180

service:
  type: ClusterIP
  port: 8080

# name of instances
name: assemble-backstage

postgres:
  external: false
  ## Use presistent storage
  storage:
    enabled: true
    size: 2G
    storageClass: ""
    ## Paas Required config
    #storageClass: "aws-efs-tier-c3"
    #labels:
    #  paas.redhat.com/appcode: "ASBL-001"
  database_user: postgres
  database_name: postgres
  ## If using external db set the host
  #database_host: "example.com"

  ## Password will be autogenerated if left empty
  ## If using extrnal instance supply the password
  # database_password: "somepassword"
  database_port: 5432
  image: registry.redhat.io/rhel9/postgresql-13:1-73
  resources:
    limits:
      cpu: 400m
      memory: 596Mi
    requests:
      cpu: 100m
      memory: 128Mi
resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template

#securityContext: restricted

## There is a secret created via the template/
backstage:
  companyName: "My Company"
  port: 7007
  # The base URL for the frontend application e.g. https://<hostname>
  baseUrl: ""

  # Ignore NodeJS insecure certificate warnings
  tlsInsecure: false

  database:
    client: pg
    connection:
      host: "${POSTGRES_HOST}"
      port: "${POSTGRES_PORT}"
      user: "${POSTGRES_USER}"
      password: "${POSTGRES_ADMIN_PASSWORD}"

  ## Override Catalog with here
  catalog:
    #import:
    #  entityFilename: /examples/catalog-info.yaml
    #  pullRequestBranchName: backstage-integration
    rules:
      - allow: [Component, System, API, Resource, Location]
    locations:
      # Local example data, file locations are relative to the backend process, typically `packages/backend`
      #- type: file
      #  target: /examples/entities.yaml

      # Local example template
      #- type: file
      #  target: /examples/template/template.yaml
      #  rules:
      #    - allow: [Template]

      # Local example organizational data
      #- type: file
      #  target: /examples/org.yaml
      #  rules:
      #    - allow: [User, Group]

      - type: url
        target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-components.yaml

      # JanusIDP Quarkus Template
      - type: url
        target: https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/quarkus-web-template/template.yaml
        rules:
          - allow: [Template]
      # Backstage example systems
      #- type: url
      #  target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-systems.yaml

      # Backstage example APIs
      #- type: url
      #  target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-apis.yaml

      # Backstage example resources
      #- type: url
      #  target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-resources.yaml

      # Backstage example organization groups
      #- type: url
      #  target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/org.yaml

      # Backstage example templates
      #- type: url
      #  target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml
      #  rules:
      #    - allow: [Template]

## Creates additional config that is passed to backstage
additionalConfig: {}
