apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/{{ .Values.git.infraOrgName }}/janus-platforms.git
    targetRevision: {{ .Values.git.infraRevision }}
    path: charts/devspaces
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-devspaces
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 10s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
      limit: 15
  ignoreDifferences:
  - group: org.eclipse.che
    kind: CheCluster
    name: devspaces
    jsonPointers:
    - /spec
