apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ .Values.keycloak.client.name }}
  labels:
    {{- include "rhsso-backstage.labels" . | nindent 4 }}
spec:
  realmSelector:
    matchLabels:
      {{- include "rhsso-backstage.selectorLabels" . | nindent 6 }}
  serviceAccountClientRoles:
    realm-management:
      - query-groups
      - query-users
      - view-users
  client:
    clientId: {{ .Values.keycloak.client.name }}
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    defaultClientScopes:
      - profile
      - email
      - roles
    consentRequired: false
    serviceAccountsEnabled: true
    redirectUris:
      - {{ required "Backstage host is required" (printf "https://%s/oauth2/callback" .Values.backstage.host) }}
{{- if .Values.openshift.clusterDomain }}
      - https://oauth-openshift.apps.{{ .Values.openshift.clusterDomain }}/*
{{- end }}
