apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Release.Name }}-github-creds
spec:
  vaultSecretDefinitions:
    - authentication:
        path: kubernetes
        role: policy-admin
        serviceAccount:
          name: default
      name: githubcreds
      path: "kv/{{ .Values.janusInstanceName }}/github-plugin"
  output:
    name: vault-github-plugin-creds
    stringData:
      github_app_id: '{{ "{{" }} .githubcreds.app_id {{ "}}" }}'
      github_org: '{{ "{{" }} .githubcreds.org {{ "}}" }}'
      ssh-privatekey: '{{ "{{" }} .githubcreds.private_key {{ "}}" }}'
    type: kubernetes.io/ssh-auth
